### PR TITLE
feat: add possibility to disable resources creation

### PR DESCRIPTION
**Pull request by SweetOps**
## what
* add possibility to disable resources creation

## why
* useful for multi-workspaces terraform projects

### CODE REVIEW

**Comment by SweetOps** [comment]
@osterman would be nice to get code review

**Comment by Gowiem** [comment]
@SweetOps Can you resolve these conflicts? Thanks man.

**Comment by SweetOps** [comment]
@Gowiem fixed

btw, I've several open PR's in others repos which are stuck... would be to merge them also
https://github.com/cloudposse/terraform-aws-route53-cluster-zone/pull/27
https://github.com/cloudposse/terraform-aws-ec2-instance-group/pull/10
https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/87

**Comment by Gowiem** [comment]
@SweetOps Thanks for the contribution! Released as [0.14.0](https://github.com/cloudposse/terraform-aws-vpc/releases/tag/0.14.0).

**Comment by Gowiem** [comment]
@SweetOps Regarding your other PRs, we'll get to em as fast as we can 😄

**Pull request merged**
