### PR TITLE
Fix output description 

### PR DESCRIPTION
**Pull request by ngoyal16**
## what
* IPv6 related description typo fix

## why
* In IPv6 related outputs vars description contains IPv4 instead of IPv6

### CODE REVIEW

**Comment by joe-niland** [comment]
Hi @ngoyal16 could you please fill out the PR template and also make your changes in `outputs.tf`? The docs are auto-generated.

**Comment by ngoyal16** [comment]
@joe-niland  i have updated MR template also update the changes in output.tf

**Review by joe-niland — APPROVED** [review]

**Comment by ngoyal16** [comment]
@joe-niland when this can be merged

**Pull request merged**
