### PR TITLE
Add an optional boolean flag to requests an Amazon-provided IPv6 CIDR…

### PR DESCRIPTION
**Pull request by stephanevalk**
## what
Add an optional boolean flag to requests an Amazon-provided IPv6 CIDR block

## why
IPV6 CIDR BLock is not always necessary.
## references
https://www.terraform.io/docs/providers/aws/r/vpc.html

This has been tested without any issue as described in https://github.com/cloudposse/terraform-aws-vpc/pull/28

### CODE REVIEW

**Comment by Gowiem** [comment]
@stephanevalk Can you fix your merge conflicts here? Also, please read through #15. Seems there was an issue with this flag in the past which I just found. Have you tested this update? Want to make sure we don't create problems with this.

**Comment by stephanevalk** [comment]
Let me check again the potential #15 issue and resolve the conflicts. Coming back to you.

**Comment by aknysh** [comment]
@stephanevalk please rebase

**Comment by brianredbeard** [comment]
Assuming this gets merged, it should resolve #59

**Comment by woz5999** [comment]
@stephanevalk this PR has merge conflicts. once those are resolved we can re-review and merge

**Comment by aknysh** [comment]
@stephanevalk please rebase

**Comment by 1david5** [comment]
This has been addressed in PR #81

**Comment by Gowiem** [comment]
Fixed via #81

**Pull request closed without merging**
