### PR TITLE
Pass `environment` argument to label module

### PR DESCRIPTION
**Pull request by guigo2k**
According to [terraform-null-label](https://github.com/cloudposse/terraform-null-label), a label follows the following naming convention: ` {namespace}-{environment}-{stage}-{name}-{attributes}`. However, using the `environment` argument in this module produces an error:
```
An argument named "environment" is not expected here.
```
This pull request fixes this error by passing `environment` as an argument to the label module.

### CODE REVIEW

**Comment by ckoning** [comment]
+1 on this. We would like to use the `environment` param and tag for consistency with the rest of our modules.

**Comment by maximmi** [comment]
@guigo2k please, update PR and address the comments

**Comment by etwillbefine** [comment]
obsolete due to https://github.com/cloudposse/terraform-aws-vpc/pull/48

**Comment by Gowiem** [comment]
Closing out as `environment` was supported as part of #48. Regardless, thanks for the effort @guigo2k!

**Pull request closed without merging**
